import './globals.css'
import type { Metadata } from 'next'
import { Montserrat, Roboto, Poppins } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-montserrat' })
// const roboto = Roboto({ subsets: ['latin'], display: 'swap' , weight: ['400', '700'], variable: '--font-roboto'})
// const poppins = Poppins({ subsets: ['latin'], display: 'swap' , weight: ['400', '700'], variable: '--font-poppins'})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
      
    </html>
  )
}
